### PR TITLE
[FIX] Change package.json to enable require

### PR DESCRIPTION
**Pull request by VikramjeetD**
A line of code in `package.json` was disabling usage of `require`. 
No other changes have been made. 
This needs to be merged asap

### CODE REVIEW

**Comment by Kushagra-0801** [comment]
require is older syntax you can change it to use import

**Comment by Kushagra-0801** [comment]
changing package.json would break the rest of the code base

**Comment by VikramjeetD** [comment]
> require is older syntax you can change it to use import

@Kushagra-0801 
`import` is causing a lot of problems. Most of the documentation everywhere (specially for google oauth) uses this. 
We haven't written a whole lot of code on `dev` branch yet. The only open PR that would need change is #15 . I suggest we do this. No other changes are needed.

**Comment by Kushagra-0801** [comment]
but we had agreed on ES6!!

**Pull request closed without merging**
