### PR TITLE
Add landing page UI

### PR DESCRIPTION
**Pull request by VikramjeetD**
- Add basic landing page UI, to enable adding routes for login. 
- Testbed button has been kept to bypass login and test any ui component/page. 

**Do not merge until #16 is merged and updates are made to this PR.**

### CODE REVIEW

**Review by AetherPrior — COMMENTED** [review]
@Aviral14 @Kushagra-0801 I think this is fine?

Sorry to hijack this PR, but react-router-dom requires only stateless components AFAIK. So I'm not sure how I can route my Preview TT to a new page, without having to have a stateless "helper component" to deal with it. 
Is that okay with you guys @VikramjeetD @Aviral14 @Kushagra-0801 ?

**Comment by VikramjeetD** [comment]
> @Aviral14 @Kushagra-0801 I think this is fine?
> 
> Sorry to hijack this PR, but react-router-dom requires only stateless components AFAIK. So I'm not sure how I can route my Preview TT to a new page, without having to have a stateless "helper component" to deal with it.
> Is that okay with you guys @VikramjeetD @Aviral14 @Kushagra-0801 ?

Do you have any alternative?

**Comment by AetherPrior** [comment]
My workaround was to maintain a state which stored which view to use. Aside from this we *can* however make helper functions that we can pass to react-router-dom afaik

**Comment by VikramjeetD** [comment]
Me and @Aviral14 were thinking along the lines of your second suggestion. 

The app itself (`App.js`) can be stateless, and only going to define the routes. Each of them is going to be to a stateless component. These components would define the layout of a page, among which we can use your stateful components. 
So the hierarchy would somewhat be like
```
App.js 
|__timetableCreation
    |__ Dashboard
    |    |__ courseSelection
    |    |__ timetableDisplay
    |__ other stuff (navbar etc)
```

Not exactly sure if we would bump into any React side "restrictions", but we can give it a try.

**Comment by AetherPrior** [comment]
Cool then, no issues from my side.
Resolve all merge conflicts and make the merge

**Pull request closed without merging**
